# Generated by Django 4.1.4 on 2023-01-18 00:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0008_alter_bvn_options_alter_customerdetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_purchased', models.DateTimeField(auto_now_add=True)),
                ('Due_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('payment_status', models.CharField(choices=[('C', 'Complete'), ('P', 'Pending'), ('F', 'Failed')], default='P', max_length=1)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.customerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(choices=[('Real Asset', 'Real Asset'), ('Real Banking', 'Real Banking'), ('Real Project', 'Real Project')], max_length=200, null=True)),
                ('duration', models.DateField(null=True)),
                ('roi', models.IntegerField(null=True)),
                ('price_per_slot', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('amount', models.CharField(max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('slots_available', models.BooleanField(default=True)),
                ('decription', models.TextField(blank=True, null=True)),
                ('terms_and_condition', models.TextField(blank=True, null=True)),
                ('is_agreed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Property',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='proper.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='proper.property')),
            ],
        ),
    ]
