# Generated by Django 4.1.4 on 2023-02-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proper', '0002_investment_alter_property_duration_delete_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='roi',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
