# Generated by Django 4.1.4 on 2023-02-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proper', '0006_alter_property_slots_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_agreed',
        ),
    ]
