# Generated by Django 4.1.4 on 2023-03-05 05:01

from django.db import migrations, models
import proper.models


class Migration(migrations.Migration):

    dependencies = [
        ('proper', '0007_remove_property_is_agreed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='picture',
        ),
        migrations.AddField(
            model_name='property',
            name='pictures',
            field=models.FileField(blank=True, storage=proper.models.MyCloudinaryStorage(), upload_to='images'),
        ),
    ]
