# Generated by Django 4.1.4 on 2023-03-05 08:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proper', '0008_remove_property_picture_property_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='pictures',
        ),
        migrations.AddField(
            model_name='property',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='proper.imagemodel'),
        ),
    ]
