# Generated by Django 4.1.4 on 2023-03-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proper', '0009_imagemodel_remove_property_pictures_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='decription',
            new_name='description',
        ),
    ]
