# Generated by Django 4.1.4 on 2023-03-06 03:07

from django.db import migrations, models
import proper.models


class Migration(migrations.Migration):

    dependencies = [
        ('proper', '0010_rename_decription_property_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pictures',
        ),
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, storage=proper.models.MyCloudinaryStorage(), upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, storage=proper.models.MyCloudinaryStorage(), upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, storage=proper.models.MyCloudinaryStorage(), upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
