# Generated by Django 4.1.4 on 2023-03-06 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proper', '0011_remove_property_pictures_property_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proper.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
