# Generated by Django 4.1.4 on 2023-03-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proper', '0014_rename_reference_transaction_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
