# Generated by Django 4.1.4 on 2023-03-16 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_customerdetails_bvn_and_more'),
        ('proper', '0015_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.customerdetails'),
        ),
    ]
