# Generated by Django 4.1.4 on 2023-03-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proper', '0016_transaction_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
