# Generated by Django 4.1.4 on 2023-03-25 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proper', '0019_alter_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('bank', models.CharField(choices=[('access', 'Access Bank'), ('citibank', 'Citibank'), ('diamond', 'Diamond Bank'), ('ecobank', 'Ecobank'), ('fidelity', 'Fidelity Bank'), ('first_bank', 'First Bank'), ('fcmb', 'First City Monument Bank'), ('gtb', 'Guaranty Trust Bank'), ('heritage', 'Heritage Bank'), ('keystone', 'Keystone Bank'), ('polaris', 'Polaris Bank'), ('providus', 'Providus Bank'), ('stanbic', 'Stanbic IBTC Bank'), ('standard_chartered', 'Standard Chartered Bank'), ('sterling', 'Sterling Bank'), ('suntrust', 'Suntrust Bank'), ('union', 'Union Bank'), ('uba', 'United Bank for Africa'), ('unity', 'Unity Bank'), ('wema', 'Wema Bank'), ('zenith', 'Zenith Bank'), ('alat', 'ALAT by WEMA'), ('jubilee', 'Jubilee Bank'), ('sparkle', 'Sparkle'), ('kuda', 'Kuda Bank'), ('opay', 'OPay'), ('palmpay', 'PalmPay')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
