# Generated by Django 4.1.4 on 2023-04-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proper', '0021_transaction_payment_type_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
