# Generated by Django 4.1.4 on 2022-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_customuser_city_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bpage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fpage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
