# Generated by Django 4.1.4 on 2023-01-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_customerdetails_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bvn',
            options={'verbose_name_plural': 'Bvn'},
        ),
        migrations.AlterModelOptions(
            name='customerdetails',
            options={'verbose_name_plural': 'Customer Details'},
        ),
        migrations.AlterModelOptions(
            name='nin',
            options={'verbose_name_plural': 'Nin'},
        ),
        migrations.RemoveField(
            model_name='nin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='id',
        ),
        migrations.RemoveField(
            model_name='security',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nin',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business.customerdetails'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business.customerdetails'),
        ),
        migrations.AlterField(
            model_name='security',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business.customerdetails'),
        ),
    ]
