# Generated by Django 4.1.4 on 2023-01-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_bvn_options_alter_customerdetails_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nin',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='security',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='bpage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='bvn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='fpage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='nin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='security_answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='security_question',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Bvn',
        ),
        migrations.DeleteModel(
            name='Nin',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
    ]
