# Generated by Django 4.1.4 on 2023-03-01 17:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_nin_customer_remove_picture_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='bvn',
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='bpage',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='fpage',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='images/'),
        ),
    ]
